# Generated by Django 4.1.7 on 2023-03-16 00:50

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('yuvak_type', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('mobile_number', models.IntegerField()),
                ('date_of_birth', models.CharField(max_length=255)),
                ('sabha_location', models.CharField(max_length=255)),
                ('reference', models.CharField(max_length=255)),
                ('good_at', models.CharField(max_length=255)),
                ('hand', models.CharField(max_length=255)),
                ('tshirt_size', models.CharField(max_length=255)),
                ('tshirt_name', models.CharField(max_length=255)),
                ('payment_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('payment_type', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('payment_status', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('profile', models.FileField(blank=True, default='', upload_to=api.models.upload_path, verbose_name='profile')),
                ('auction', models.FileField(blank=True, default='', upload_to=api.models.upload_path, verbose_name='auction')),
                ('availibility', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
    ]
