# Generated by Django 4.1.7 on 2023-03-28 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_profile_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionPlayersDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('is_sold', models.BooleanField(blank=True, default=0, null=True)),
                ('sold_to', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('sold_on', models.IntegerField()),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profile')),
            ],
        ),
    ]
