# Generated by Django 4.1.7 on 2023-03-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_auctionplayersdetails_sold_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamAuthentication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=255)),
                ('team_password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TeamSelection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('team_name', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
    ]
